const API_URL = "http://localhost:8000/index.php";

async function fetchHubData() {
  try {
    const response = await fetch(API_URL);

    if (!response.ok) {
      throw new Error(`Erreur serveur : ${response.status}`);
    }

    const data = await response.json();

    document.getElementById("pseudo").textContent = data.pseudo;
    document.getElementById("description").textContent = data.description;

    // Inject HTML generated by the backend
    document.getElementById("links-container").innerHTML = data.linksHtml;
    document.getElementById("videos-container").innerHTML = data.videosHtml;

  } catch (error) {
    console.error("Impossible de récupérer les données :", error);
    document.getElementById("pseudo").textContent = "Erreur de chargement";
  }
}

document.addEventListener("DOMContentLoaded", fetchHubData);
