services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:z
    networks:
      - exon-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html:z
    networks:
      - exon-network

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "composer install && php init_db.php && chmod 777 database.sqlite && chmod 777 . && ./vendor/bin/phpunit"
    volumes:
      - ./backend:/var/www/html:z
    networks:
      - exon-network
    depends_on:
      - backend

networks:
  exon-network:
    driver: bridge
